version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  node:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - run: |
          node --version
          npm --version

workflows:
  build:
    jobs:
      - node
