version: 2.1

# Dynamic Configuration
setup: true

orbs:
  cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@0.2.0

jobs:
  pack:
    executor: continuation/default
    steps:
      - checkout
      - cli/install
      - run: circleci config pack .circleci/config_pack > .circleci/packed.yml
      - continuation/continue:
          configuration_path: .circleci/packed.yml
  yq:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Install yq
          command: |
            curl -Lo yq https://github.com/mikefarah/yq/releases/download/v4.12.2/yq_linux_amd64
            chmod +x yq
      - run: yq ea '. as $item ireduce ({}; . * $item )' .circleci/config_yq/config_* > .circleci/merged.yml
      - continuation/continue:
          configuration_path: .circleci/merged.yml

workflows:
  setup:
    jobs:
      # - pack
      - yq
