version: 2.1

# Dynamic Configuration
setup: true

orbs:
  cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - cli/install
      - run: circleci config pack .circleci/config_pack > .circleci/packed.yml
      - continuation/continue:
          configuration_path: .circleci/packed.yml

workflows:
  setup:
    jobs:
      - setup
