version: 2.1

# Dynamic Configuration
setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup_node:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/config_node.yml
  setup_java:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/config_gradle.yml

workflows:
  welcome:
    jobs:
      - setup_node
      - setup_gradle
